// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjJHc9YACPirJ24l8wBbtIn06SjtbSI6U',
    appId: '1:667612856236:web:7c8a768b8fdd765051c409',
    messagingSenderId: '667612856236',
    projectId: 'quiz-app-8e661',
    authDomain: 'quiz-app-8e661.firebaseapp.com',
    storageBucket: 'quiz-app-8e661.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYOr9OFreKBePtbQp1Gf5Pp22w3cz6GAc',
    appId: '1:667612856236:android:d8ffc26cf9e7e4ab51c409',
    messagingSenderId: '667612856236',
    projectId: 'quiz-app-8e661',
    storageBucket: 'quiz-app-8e661.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCo9ipx1phAFZy8hL7-TaeBLCgaSk6w4g',
    appId: '1:667612856236:ios:2d172c4366e39c0d51c409',
    messagingSenderId: '667612856236',
    projectId: 'quiz-app-8e661',
    storageBucket: 'quiz-app-8e661.firebasestorage.app',
    iosBundleId: 'com.example.quizApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCo9ipx1phAFZy8hL7-TaeBLCgaSk6w4g',
    appId: '1:667612856236:ios:2d172c4366e39c0d51c409',
    messagingSenderId: '667612856236',
    projectId: 'quiz-app-8e661',
    storageBucket: 'quiz-app-8e661.firebasestorage.app',
    iosBundleId: 'com.example.quizApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCjJHc9YACPirJ24l8wBbtIn06SjtbSI6U',
    appId: '1:667612856236:web:fd9b940da730478651c409',
    messagingSenderId: '667612856236',
    projectId: 'quiz-app-8e661',
    authDomain: 'quiz-app-8e661.firebaseapp.com',
    storageBucket: 'quiz-app-8e661.firebasestorage.app',
  );
}
